name: buddycount_landing
description: "Professional landing page for BuddyCount - a shared budget management app"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/screenshots/
